remove deprecated loc
emberjs/ember-string pull request #28
Opened 2019-01-28 11:35 UTC by locks

2021-07-27 18:24 UTC, stefanpenner commented
@locks I've made some changes, does this seem correct?

2021-07-27 18:25 UTC, stefanpenner requested changes

2021-07-27 18:25 UTC, stefanpenner commented on tests/typings/test.ts
> +  decamelize, getStrings, loc, setStrings,
remove `loc`

2021-09-03 18:54 UTC, kategengler commented
Handled in #270

2021-09-03 18:54 UTC, closed without merging